# Generated by Django 5.1.5 on 2025-01-30 10:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosenPackage', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Yearly', 'Yearly')], default='Daily', max_length=10)),
                ('payAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('schemeCode', models.CharField(editable=False, max_length=20, unique=True)),
                ('joiningDate', models.DateField(default=django.utils.timezone.now)),
                ('totalAmountPaid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalGold', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('NumberOfTimesPaid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('phoneNumbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_schemes', to='goldLoan.user')),
            ],
        ),
    ]
