# Generated by Django 5.1.5 on 2025-01-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinscheme',
            name='phoneNumbers',
        ),
    ]
