# Generated by Django 5.1.5 on 2025-01-31 04:38

import django.utils.timezone
import goldLoan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0002_remove_joinscheme_phonenumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedsTitle', models.CharField(max_length=125)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feeds/%Y/%m/%d/')),
                ('context', models.TextField(help_text='Content of the feed post')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('joiningDate', models.DateField(default=goldLoan.models.get_current_date)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='joinscheme',
            name='joiningDate',
            field=models.DateField(default=goldLoan.models.get_current_date),
        ),
    ]
