# Generated by Django 5.1.5 on 2025-01-31 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0003_feeds_alter_joinscheme_joiningdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinscheme',
            name='phone',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, related_name='join_schemes', to='goldLoan.user'),
            preserve_default=False,
        ),
    ]
