# Generated by Django 5.1.5 on 2025-01-31 06:04

import django.core.validators
import django.db.models.deletion
import goldLoan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0004_joinscheme_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField(default=goldLoan.models.get_current_date)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goldAdded', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('schemeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='goldLoan.joinscheme')),
            ],
        ),
    ]
