# Generated by Django 5.1.5 on 2025-01-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinscheme',
            name='chosenPackage',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=10),
        ),
    ]
