# Generated by Django 5.1.5 on 2025-01-31 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0006_alter_joinscheme_chosenpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinscheme',
            name='remainingPayments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
