# Generated by Django 5.1.5 on 2025-02-05 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0008_liveprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveprice',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Live Price', 'verbose_name_plural': 'Live Prices'},
        ),
        migrations.RemoveField(
            model_name='liveprice',
            name='silver_prive',
        ),
        migrations.AddField(
            model_name='liveprice',
            name='silver_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liveprice',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='liveprice',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
