# Generated by Django 5.1.5 on 2025-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0010_remove_user_phone_user_email_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1111, max_length=128),
            preserve_default=False,
        ),
    ]
