# Generated by Django 5.1.5 on 2025-02-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0012_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('id', 'phone_number')},
        ),
    ]
