# Generated by Django 5.1.5 on 2025-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0014_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('ADMIN', 'Admin User'), ('SUPERUSER', 'Super User')], default='NORMAL', max_length=10),
        ),
    ]
