# Generated by Django 5.1.5 on 2025-03-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0017_payment_payment_method_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
