# Generated by Django 5.1.5 on 2025-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0019_payment_amount_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razorpay Payment ID'),
        ),
    ]
