# Generated by Django 5.1.5 on 2025-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0020_alter_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
