# Generated by Django 5.1.5 on 2025-03-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0021_remove_payment_amount_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('poc', 'POC')], default='online', max_length=10),
        ),
    ]
