# Generated by Django 5.1.5 on 2025-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldLoan', '0022_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
